name: xixo-prueba

on:
  workflow_dispatch: # Permite ejecutar manualmente el workflow
    inputs: # Opcional: define inputs si necesitas parámetros para el workflow
      build_version:
        description: 'Build version'
        required: false
        default: 'latest'

jobs:
  build-mac:
    runs-on: macos-latest # Ejecuta en el entorno más reciente de macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Usa la versión de Node.js que necesitas

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for macOS
        run: npm run make # Cambia 'make' si usas un comando diferente para compilar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Electron-macOS-App
          path: out/make/*.dmg # Ajusta la ruta al formato de salida de tu app
