name: xixo-prueba

on:
  workflow_dispatch: # Permite ejecutar manualmente el workflow
    inputs: # Opcional: define inputs si necesitas parámetros para el workflow
      build_version:
        description: 'Build version'
        required: false
        default: 'latest'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Usa la versión de Node.js que necesitas

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run make # Cambia 'make' si usas un comando diferente para compilar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Electron-Windows-App
          path: out/make/squirrel.windows/x64/*.exe # Cambia esta ruta al output de tu app
