name: xixo-prueba

on:
  workflow_dispatch: # Permite ejecutar manualmente el workflow
    inputs: # Opcional: define inputs si necesitas parámetros para el workflow
      build_version:
        description: 'Build version'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: windows-latest # Cambia a 'windows-latest' o 'ubuntu-latest' según la plataforma
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ajusta la versión de Node.js según tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build with Electron Forge
        run: npm run make # Asegúrate que este script esté configurado en tu package.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-forge-build
          path: out/make # Ajusta según la carpeta de salida de Electron Forge
